name: bbiab
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5507
title: be back in a bit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: 'http://www.bbiab.com'
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#32251c'
    - '#816854'
    - '#ad8b75'
  brandStrength: 0.875
  lightness: 0.8611340643838048
  saturation: 0.31224305578507483
  rhythmicContrast: 0.3079398889094591
purpose: []
