name: bbiab
favicon: null
layout_spectrum: 0.46523
typography_spectrum: 0.5507
title: be back in a bit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#34526a'
    - '#e3e3e2'
    - '#3f2f28'
    - '#946e4d'
  brandStrength: 0
  lightness: 0.8611340643838048
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
