name: bbiab
favicon: null
layout_spectrum: 0.99135
typography_spectrum: 0.1638096678070724
title: be back in a bit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.8611340643838048
  saturation: 0.31224305578507483
  rhythmicContrast: 0.3079398889094591
purpose: []
